openapi: 3.0.3
info:
    title: 'Laravel-API"l'
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://localhost'
paths:
    /api/catogeries:
        get:
            summary: 'Get Catogeries'
            description: 'List all Catogeries'
            parameters:
                -
                    in: query
                    name: page
                    description: 'which page to show.'
                    example: 12
                    required: false
                    schema:
                        type: integer
                        description: 'which page to show.'
                        example: 12
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                401:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    message: Unauthenticated.
                                properties:
                                    message: { type: string, example: Unauthenticated. }
            tags:
                - Catogeries
            security: []
        post:
            summary: 'Post Catogeries'
            description: 'Create New Catoger'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Catogeries
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: ''
                                    example: facere
                            required:
                                - name
            security: []
    '/api/catogeries/{catogery}':
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                401:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    message: Unauthenticated.
                                properties:
                                    message: { type: string, example: Unauthenticated. }
            tags:
                - Catogeries
            security: []
        put:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Catogeries
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: ''
                                    example: et
                            required:
                                - name
            security: []
        delete:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Catogeries
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: ''
                                    example: qui
                            required:
                                - name
            security: []
        parameters:
            -
                in: path
                name: catogery
                description: ''
                example: impedit
                required: true
                schema:
                    type: string
    /api/product:
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    data: [{ id: 1, category_id: 990, name: quo, description: 'Aliquid et maiores sequi sint ut illum ducimus. Laudantium aut suscipit mollitia esse quia. Distinctio commodi voluptates temporibus dolores necessitatibus amet culpa.', price: '1,089.03', category: { id: 990, name: 'Shane Hickle', created_at: '2022-08-26T01:49:40.000000Z' } }, { id: 2, category_id: 639, name: porro, description: 'Quia sed explicabo dignissimos harum harum aut quia. Laudantium laboriosam ut saepe aspernatur non. Illo nisi voluptas voluptatem ducimus eum. Omnis omnis et dolorem.', price: '719.57', category: { id: 639, name: 'Leanna Wilderman', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 3, category_id: 637, name: consequatur, description: 'Nihil ea molestiae et aliquid libero ut. Ad et aut tenetur alias enim id doloremque praesentium. Hic ea id ipsum ratione a dolor corporis. Animi impedit alias sit dignissimos quae earum.', price: '981.06', category: { id: 637, name: 'Nat Denesik', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 4, category_id: 613, name: ab, description: 'Rerum voluptatem id autem ut eos necessitatibus. Et unde temporibus blanditiis similique vero. Explicabo nemo velit non eveniet autem esse. Eius sed debitis ut et sed quia facere.', price: '936.23', category: { id: 613, name: 'Mohammed Rohan', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 5, category_id: 117, name: officia, description: 'Aspernatur et ratione voluptas dolorem. Quo saepe nihil consequatur saepe voluptatum consequatur culpa. Quos accusantium minus fuga qui sit omnis debitis. Est omnis et officiis ea.', price: '901.39', category: { id: 117, name: 'Caden Connelly V', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 6, category_id: 126, name: vel, description: 'Consequuntur mollitia sapiente amet facilis. Aut et eveniet culpa cupiditate nemo officia ut expedita. Sit impedit doloremque odio est perferendis.', price: '424.28', category: { id: 126, name: 'Mr. Deshawn Sipes V', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 7, category_id: 755, name: et, description: 'Dolore est vero est nisi nulla maiores. Mollitia id corporis similique fuga et. Cupiditate harum esse repellendus ut.', price: '812.35', category: { id: 755, name: 'River Bogan', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 8, category_id: 783, name: quod, description: 'Distinctio veritatis fugiat voluptatum minima facilis quasi. Distinctio vero ullam dolorem velit ad officia. Ex ipsa aliquid quia et illum molestias quia. Sed tenetur ea aperiam porro.', price: '1,221.12', category: { id: 783, name: 'Howell Crist', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 9, category_id: 236, name: accusantium, description: 'Autem omnis amet fugiat quod nemo aliquid. Quis et eligendi atque ea vel velit. Blanditiis numquam facilis ducimus qui. Rem id fugiat consequuntur earum amet est qui.', price: '919.88', category: { id: 236, name: 'Alva Altenwerth Jr.', created_at: '2022-08-26T01:49:39.000000Z' } }]
                                    links: { first: 'http://localhost/api/product?page=1', last: 'http://localhost/api/product?page=112', prev: null, next: 'http://localhost/api/product?page=2' }
                                    meta: { current_page: 1, from: 1, last_page: 112, links: [{ url: null, label: '&laquo; Previous', active: false }, { url: 'http://localhost/api/product?page=1', label: '1', active: true }, { url: 'http://localhost/api/product?page=2', label: '2', active: false }, { url: 'http://localhost/api/product?page=3', label: '3', active: false }, { url: 'http://localhost/api/product?page=4', label: '4', active: false }, { url: 'http://localhost/api/product?page=5', label: '5', active: false }, { url: 'http://localhost/api/product?page=6', label: '6', active: false }, { url: 'http://localhost/api/product?page=7', label: '7', active: false }, { url: 'http://localhost/api/product?page=8', label: '8', active: false }, { url: 'http://localhost/api/product?page=9', label: '9', active: false }, { url: 'http://localhost/api/product?page=10', label: '10', active: false }, { url: null, label: ..., active: false }, { url: 'http://localhost/api/product?page=111', label: '111', active: false }, { url: 'http://localhost/api/product?page=112', label: '112', active: false }, { url: 'http://localhost/api/product?page=2', label: 'Next &raquo;', active: false }], path: 'http://localhost/api/product', per_page: 9, to: 9, total: 1000 }
                                properties:
                                    data: { type: array, example: [{ id: 1, category_id: 990, name: quo, description: 'Aliquid et maiores sequi sint ut illum ducimus. Laudantium aut suscipit mollitia esse quia. Distinctio commodi voluptates temporibus dolores necessitatibus amet culpa.', price: '1,089.03', category: { id: 990, name: 'Shane Hickle', created_at: '2022-08-26T01:49:40.000000Z' } }, { id: 2, category_id: 639, name: porro, description: 'Quia sed explicabo dignissimos harum harum aut quia. Laudantium laboriosam ut saepe aspernatur non. Illo nisi voluptas voluptatem ducimus eum. Omnis omnis et dolorem.', price: '719.57', category: { id: 639, name: 'Leanna Wilderman', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 3, category_id: 637, name: consequatur, description: 'Nihil ea molestiae et aliquid libero ut. Ad et aut tenetur alias enim id doloremque praesentium. Hic ea id ipsum ratione a dolor corporis. Animi impedit alias sit dignissimos quae earum.', price: '981.06', category: { id: 637, name: 'Nat Denesik', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 4, category_id: 613, name: ab, description: 'Rerum voluptatem id autem ut eos necessitatibus. Et unde temporibus blanditiis similique vero. Explicabo nemo velit non eveniet autem esse. Eius sed debitis ut et sed quia facere.', price: '936.23', category: { id: 613, name: 'Mohammed Rohan', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 5, category_id: 117, name: officia, description: 'Aspernatur et ratione voluptas dolorem. Quo saepe nihil consequatur saepe voluptatum consequatur culpa. Quos accusantium minus fuga qui sit omnis debitis. Est omnis et officiis ea.', price: '901.39', category: { id: 117, name: 'Caden Connelly V', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 6, category_id: 126, name: vel, description: 'Consequuntur mollitia sapiente amet facilis. Aut et eveniet culpa cupiditate nemo officia ut expedita. Sit impedit doloremque odio est perferendis.', price: '424.28', category: { id: 126, name: 'Mr. Deshawn Sipes V', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 7, category_id: 755, name: et, description: 'Dolore est vero est nisi nulla maiores. Mollitia id corporis similique fuga et. Cupiditate harum esse repellendus ut.', price: '812.35', category: { id: 755, name: 'River Bogan', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 8, category_id: 783, name: quod, description: 'Distinctio veritatis fugiat voluptatum minima facilis quasi. Distinctio vero ullam dolorem velit ad officia. Ex ipsa aliquid quia et illum molestias quia. Sed tenetur ea aperiam porro.', price: '1,221.12', category: { id: 783, name: 'Howell Crist', created_at: '2022-08-26T01:49:39.000000Z' } }, { id: 9, category_id: 236, name: accusantium, description: 'Autem omnis amet fugiat quod nemo aliquid. Quis et eligendi atque ea vel velit. Blanditiis numquam facilis ducimus qui. Rem id fugiat consequuntur earum amet est qui.', price: '919.88', category: { id: 236, name: 'Alva Altenwerth Jr.', created_at: '2022-08-26T01:49:39.000000Z' } }], items: { type: object } }
                                    links: { type: object, example: { first: 'http://localhost/api/product?page=1', last: 'http://localhost/api/product?page=112', prev: null, next: 'http://localhost/api/product?page=2' } }
                                    meta: { type: object, example: { current_page: 1, from: 1, last_page: 112, links: [{ url: null, label: '&laquo; Previous', active: false }, { url: 'http://localhost/api/product?page=1', label: '1', active: true }, { url: 'http://localhost/api/product?page=2', label: '2', active: false }, { url: 'http://localhost/api/product?page=3', label: '3', active: false }, { url: 'http://localhost/api/product?page=4', label: '4', active: false }, { url: 'http://localhost/api/product?page=5', label: '5', active: false }, { url: 'http://localhost/api/product?page=6', label: '6', active: false }, { url: 'http://localhost/api/product?page=7', label: '7', active: false }, { url: 'http://localhost/api/product?page=8', label: '8', active: false }, { url: 'http://localhost/api/product?page=9', label: '9', active: false }, { url: 'http://localhost/api/product?page=10', label: '10', active: false }, { url: null, label: ..., active: false }, { url: 'http://localhost/api/product?page=111', label: '111', active: false }, { url: 'http://localhost/api/product?page=112', label: '112', active: false }, { url: 'http://localhost/api/product?page=2', label: 'Next &raquo;', active: false }], path: 'http://localhost/api/product', per_page: 9, to: 9, total: 1000 } }
            tags:
                - Products
            security: []
    /api/register:
        post:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - User
            security: []
    /api/loginUser:
        post:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - User
            security: []
